# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      with:
        gradle-version: '8.6'
        
    - name: Build with Gradle Wrapper
      run: |
        chmod +x v1.8.9/gradlew
        cd v1.8.9
        ./gradlew build

    - name: Upload v1.8.9 artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: v1.8.9
        path: v1.8.9/build/libs/

    - name: Build with Gradle Wrapper
      run: |
        chmod +x v1.12.2/gradlew
        cd v1.12.2
        ./gradlew build

    - name: Upload v1.12.2 artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: v1.12.2
        path: v1.12.2/build/libs/

